apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: pdm
resources:
  - namespace.yaml
  - configmap.yaml
  - pvc.yaml
  - deployment-api.yaml
  - service-api.yaml
  - hpa.yaml
  - deployment-dashboard.yaml
  - service-dashboard.yaml
  - cronjob-monitor.yaml
